/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI; 
import Conexion.*;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;

/**
 *
 * @author antonio
 */
public class VentaCliente extends javax.swing.JFrame {
    private CallbackClientInterface cbi;
    private CallbackServerInterface csi;
        
    /**
     * Creates new form VentaCliente
     */
    public VentaCliente() {
        initComponents();
    }

    public JTextArea getTxtAlerta() {
        return txtAlerta;
    }

    public void setTxtAlerta(JTextArea txtAlerta) {
        this.txtAlerta = txtAlerta;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        taboa = new javax.swing.JTable();
        bntAct = new javax.swing.JButton();
        btnCompra = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        txtEmpresa = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAlerta = new javax.swing.JTextArea();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventá Cliente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        taboa.setModel(new ModeloTaboa()
        );
        taboa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taboaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(taboa);

        bntAct.setText("Actualizar");
        bntAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntActActionPerformed(evt);
            }
        });

        btnCompra.setText("Alerta de Compra");
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });

        btnVenta.setText("Alerta de Venta");
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });

        txtEmpresa.setEditable(false);
        txtEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpresaActionPerformed(evt);
            }
        });

        jLabel1.setText("Empresa");

        jLabel2.setText("Valor");

        txtAlerta.setColumns(20);
        txtAlerta.setRows(5);
        jScrollPane3.setViewportView(txtAlerta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(bntAct)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCompra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnVenta))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 140, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(135, 135, 135))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(235, 235, 235))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(204, 204, 204))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(239, 239, 239)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntAct)
                            .addComponent(btnVenta)
                            .addComponent(btnCompra))
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bntActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntActActionPerformed
        // TODO add your handling code here:
        HashMap<String, Double> taboa = null;
        try {
            taboa = csi.getTaboa();
        } catch (RemoteException ex) {
            Logger.getLogger(VentaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        Set<String> empresas = taboa.keySet();
        Collection<Double> valores = taboa.values();
        ArrayList<String> AEmpresas = new ArrayList(empresas);
        ArrayList<Double> AValores = new ArrayList(valores);
        this.mostrarTaboa(AEmpresas, AValores);
        System.out.println("táboa actualizada");
    }//GEN-LAST:event_bntActActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            // TODO add your handling code here:
            csi.unregisterForCallback(cbi);
        } catch (RemoteException ex) {
            Logger.getLogger(VentaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("Rexistro cancelado");
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            csi.unregisterForCallback(cbi);
        } catch (RemoteException ex) {
            Logger.getLogger(VentaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("Rexistro cancelado");
    }//GEN-LAST:event_formWindowClosing

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        // TODO add your handling code here:
        ModeloTaboa m;
        m = (ModeloTaboa) taboa.getModel();
        double d = Double.parseDouble(txtValor.getText());
        try {
            csi.alertaCompra(txtEmpresa.getText(), d, cbi);
        } catch (RemoteException ex) {
            Logger.getLogger(VentaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtEmpresa.setText("");
        txtValor.setText("");
    }//GEN-LAST:event_btnCompraActionPerformed

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        // TODO add your handling code here:
        ModeloTaboa m;

        m = (ModeloTaboa) taboa.getModel();
        double d = Double.parseDouble(txtValor.getText());
        try {
            csi.alertaVenta(txtEmpresa.getText(), d, cbi);
        } catch (RemoteException ex) {
            Logger.getLogger(VentaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtEmpresa.setText("");
        txtValor.setText("");
    }//GEN-LAST:event_btnVentaActionPerformed

    private void txtEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpresaActionPerformed

    private void taboaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taboaMouseClicked
        // TODO add your handling code here:
        ModeloTaboa m;

        m = (ModeloTaboa) taboa.getModel();
        txtEmpresa.setText(m.obterEmpresa(taboa.getSelectedRow()));
    }//GEN-LAST:event_taboaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentaCliente vc = new VentaCliente();
                vc.setVisible(true);
                VRexistro vx = new VRexistro(vc, true, vc);
                vx.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAct;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable taboa;
    private javax.swing.JTextArea txtAlerta;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables


    private void mostrarTaboa(ArrayList<String> empresas, ArrayList<Double> valores){
        ModeloTaboa m;

        m = (ModeloTaboa) taboa.getModel();
        m.setFilas(empresas, valores);
        if (m.getRowCount() > 0) {
            taboa.setRowSelectionInterval(0, 0);
        }
    }
    
    public void start(String hostNum, String portNum){
        try {
      int RMIPort;
      String registryURL = 
        "rmi://localhost:" + portNum + "/callback";  
      // find the remote object and cast it to an 
      //   interface object
      CallbackServerInterface h =
        (CallbackServerInterface)Naming.lookup(registryURL);
      System.out.println("Lookup completed " );
      System.out.println("Server said " + h.sayHello());
      HashMap<String, Double> taboa = h.getTaboa();
      Set<String> empresas = taboa.keySet();
      Collection<Double> valores = taboa.values();
      ArrayList<String> AEmpresas = new ArrayList(empresas);
      ArrayList<Double> AValores = new ArrayList(valores);
      this.mostrarTaboa(AEmpresas, AValores);
      System.out.println("*****************IBEX35*****************\n" + h.getTaboa());
      CallbackClientInterface callbackObj = 
        new CallbackClientImpl(this);
      // register for callback
      h.registerForCallback(callbackObj);
      System.out.println("Registered for callback.");
      System.out.println(taboa.get("IBERDROLA"));
      h.alertaVenta("IBERDROLA", taboa.get("IBERDROLA") - 1.0, callbackObj);
      h.alertaCompra("VISCOFAN", taboa.get("VISCOFAN") + 1.0, callbackObj);
      h.alertaVenta("NATURGY", taboa.get("NATURGY") - 1.5, callbackObj);
//      try {
//        Thread.sleep(time * 1000);
//      }
//      catch (InterruptedException ex){ // sleep over
//      }
      //locawhile(i == 0){}
      //h.unregisterForCallback(callbackObj);
      this.cbi = callbackObj;
      this.csi = h;
      //System.out.println("Unregistered for callback.");
    } // end try 
    catch (Exception e) {
      System.out.println(
        "Exception in CallbackClient: " + e);
    } // end catch
    }


}
